### PR TITLE
Ignore call to process.getuid if in Windows

### LINKED ISSUE #9: Doesn't work on windows. process.getuid is not defined
I noticed that a lot of the other parts of npmd have support for windows, but it seems that npmd-install is the only one that doesn't have a functional check for it. Any ideas on how this can be alleviated? Would a PR be welcome?

### PR DESCRIPTION
**Pull request by RangerMauve**
This should fix support for Windows. Running the example in the readme seems to run without any errors.

Fixes #9

### CODE REVIEW

**Comment by dominictarr** [comment]
did you mean to close this? this pr seems reasonable.

**Comment by RangerMauve** [comment]
It seemed like it wasn't going to get anywhere anytime soon and I was just cleaning up my pending PRs. If you think it's going to be useful, I'm fine with reopening it and fixing anything it might be missing.

**Comment by dominictarr** [comment]
oh sorry, I just missed it i think. sometimes I get lots of github emails etc. I'm gonna merge this. sorry it took so long.

**Comment by dominictarr** [comment]
sorry, actually it looks like this might be fixed already. master already has code to check this.

1ca6e00f0d7393a19acb436afe7101fd2bf3329b

that should work, right?

**Comment by RangerMauve** [comment]
Yeah, looks good

**Comment by dominictarr** [comment]
okay good. Closing.

**Pull request closed without merging**
